[build]
    command = "export CI=false && yarn build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "22"

[[headers]]
    for = "/*"
    [headers.values]
    cache-control = '''
        max-age=0,
        must-revalidate'''